GET http://localhost:1337/api/musiques

###
GET http://localhost:1337/api/interpretes

###
POST http://localhost:1337/api/interpretes
Content-Type: application/json

{
  "data": {
    "nom": "Bellakath",
    "prenom": "",
    "naissance": "1998-10-05"
  }
}


###
POST http://localhost:1337/api/musiques
Content-Type: application/json

{
    "data": {
        "title": "Reggaeton Champagne",
        "link": "https://www.youtube.com/watch?v=h6qbOjac8qo",
        "interpretes": 1,
        "favorite": true,
        "release": "2023-10-25",
        "color": "170F11"
    }
}

###
POST http://localhost:1337/api/musiques
Content-Type: application/json

{
    "data": {
        "title": "Baticano",
        "link": "https://www.youtube.com/watch?v=QCqc3k0Tzbs",
        "interpretes": 2,
        "favorite": false,
        "release": "2023-03-10",
        "color": "170F11"
    }
}

###
GET http://localhost:1337/api/musiques?populate=*&sort=title:asc

###
GET http://localhost:1337/api/musiques?populate=*&filters[favorite][$eq]=true

###
GET http://localhost:1337/api/interpretes?populate=nom

###
GET http://localhost:1337/api/interpretes

###
GET http://localhost:1337/api/musiques?filters[id][$eq]=1